repos:
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: Jupyter Notebook Output Cleanup
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
