#!/usr/bin/env python3
"""
TODO
"""

import argparse


def nat_int(s: str) -> int:
    """Type validator for natural integers."""
    int_val = int(s)
    if int_val < 1:
        raise argparse.ArgumentTypeError("Cannot be less than 1")
    return int_val


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Python frontend to QST.")

    parser.add_argument(
        "--cols",
        action="store",
        metavar="COLS",
        help="Columns to pass through to the CSV",
    )

    parser.add_argument(
        "-m",
        "--method",
        action="store",
        metavar="METHOD",
        help="Sorting method for this test run",
    )

    parser.add_argument(
        "-o",
        "--output",
        action="store",
        metavar="FILE",
        help="Output to FILE instead of STDOUT",
    )

    parser.add_argument(
        "-r",
        "--runs",
        action="store",
        metavar="n",
        default=1,
        help="Number of times to sort the same data.",
    )

    return parser
