/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qst.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class QSTTest {
    @Test void appHasAGreeting() {
        QST classUnderTest = new QST();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
