---
- name: Hybrid Sorting Optimization Deploy
  hosts: all

  vars:
    base_path: /HSO
    virtualenv_path: "{{ base_path }}/env"
    virtualenv_py_path: "{{ virtualenv_path }}/bin/python"
    hso_path: "{{ base_path }}/Hybrid-Sorting-Optimization"

    data_path: "{{ hso_path }}/data"
    data_size: "50_000"

    job_parameters_list:
      - "{{ hso_path }}/src/c/HSO-c"
      - "{{ data_path }}"
      - "--methods qsort,msort_heap,msort_heap_with_old_ins,msort_heap_with_basic_ins,msort_with_network"
      - "--threshold 1,20,1"
      - "--runs 100"
    job_parameters: "{{ job_parameters_list | join(' ') }}"

  tasks:
    - name: Install build dependencies
      apt:
        autoclean: yes
        name:
          - clang
          - git
          - python3.9
          - python3-venv
          - tmux
          - zlib1g
          - zlib1g-dev
        update_cache: yes
      become: true

    - name: Query FS
      ansible.builtin.stat:
        path: "{{ base_path }}"
      register: base_path_stat

    - name: Setup FS
      ansible.builtin.file:
        path: "{{ base_path }}"
        state: directory
        mode: 0755
        owner: "{{ ansible_real_user_id }}"
        group: "{{ ansible_real_group_id }}"
      when: base_path_stat.isdir is not defined or base_path_stat.stat.isdir == False
      become: true

    - name: Clone Project
      git:
        repo: git@github.com:uwyo-mallet/Hybrid-Sorting-Optimization
        dest: "{{ hso_path }}"
        clone: yes

    - name: Build C frontend
      make:
        chdir: "{{ hso_path }}/src/c"
        params: CC=clang
        target: all

    - name: Query virtual env
      ansible.builtin.stat:
        path: "{{ virtualenv_path }}"
      register: virtualenv_path_stat

    - name: Create virtual env
      ansible.builtin.pip:
        virtualenv: "{{ virtualenv_path }}"
        virtualenv_python: "python3.9"
        requirements: "{{ hso_path }}/requirements.txt"
      when: virtualenv_path_stat.isdir is not defined or virtualenv_path_stat.stat.isdir == False

    - name: Create data directory
      ansible.builtin.shell: "{{ virtualenv_py_path }} src/data.py generate -o {{ data_path }} -t {{ data_size }}"
      args:
        chdir: "{{ hso_path }}"
        creates: "{{ data_path }}"

    - name: Create results directory
      ansible.builtin.shell: "mkdir {{ hso_path }}/results"
      args:
        chdir: "{{ hso_path }}"
        creates: "{{ hso_path }}/results"

    - name: Run job in tmux session
      ansible.builtin.shell:
        chdir: "{{ hso_path }}"
        cmd: "tmux new-session -d -s hso-session '{{ virtualenv_py_path }} src/jobs.py {{ job_parameters }} 2>&1 | tee log'"
