---
- name: Hybrid Sorting Optimization Fetch Results
  hosts: all
  user: jarulsam

  vars:
    base_path: "{{ ansible_env.HOME }}/HSO"
    hso_path: "{{ base_path }}/Hybrid-Sorting-Optimization"
    results_path: "{{ hso_path }}/results"

  tasks:
    - name: Install dependencies
      apt:
        autoclean: yes
        name:
          - rsync
        update_cache: yes
      become: true

    - name: Fetch results
      ansible.posix.synchronize:
        archive: true
        mode: "pull"
        src: "{{ results_path }}"
        dest: "../../"
